"""
AI-generated content detection module for TruthShield Fake News Detector.

Uses statistical text features — vocabulary richness, sentence burstiness,
repeated-phrase density, pronoun usage, hedge-word frequency, paragraph
structure uniformity, and character-level entropy — to estimate whether
content was generated by an AI language model.
"""

import re
import math
from collections import Counter
from typing import Dict, List


class AIContentDetector:
    """Detects AI-generated text using statistical linguistic features."""

    _HEDGE_PHRASES: List[str] = [
        "however", "moreover", "furthermore", "additionally", "consequently",
        "it is worth noting", "it is important to note", "in conclusion",
        "in summary", "notably", "significantly", "essentially",
        "fundamentally", "interestingly", "remarkably", "undoubtedly",
        "in this context", "on the other hand", "nevertheless",
        "as a result", "in other words", "that being said",
    ]

    _FIRST_PERSON = {"i", "me", "my", "mine", "myself", "we", "us", "our", "ours"}

    def __init__(self) -> None:
        pass

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def detect(self, text: str) -> Dict:
        """
        Analyze *text* for AI-generated content characteristics.

        Returns:
            Dict with keys: is_ai_generated, ai_score, indicators, explanation.
        """
        if not text or len(text.split()) < 30:
            return self._insufficient_result()

        indicators = {
            "vocabulary_richness": self._vocabulary_richness(text),
            "burstiness": self._burstiness(text),
            "sentence_uniformity": self._sentence_uniformity(text),
            "repeated_phrase_density": self._repeated_phrases(text),
            "personal_pronoun_usage": self._pronoun_score(text),
            "hedge_word_frequency": self._hedge_score(text),
            "paragraph_uniformity": self._paragraph_uniformity(text),
            "entropy": self._entropy_score(text),
        }

        weights = {
            "vocabulary_richness": 0.10,
            "burstiness": 0.15,
            "sentence_uniformity": 0.15,
            "repeated_phrase_density": 0.10,
            "personal_pronoun_usage": 0.10,
            "hedge_word_frequency": 0.15,
            "paragraph_uniformity": 0.10,
            "entropy": 0.15,
        }

        ai_score = sum(indicators[k] * weights[k] for k in weights)
        ai_score = min(max(ai_score, 0.0), 1.0)
        is_ai = ai_score > 0.55

        rounded = {k: round(v, 3) for k, v in indicators.items()}
        explanation = self._build_explanation(is_ai, ai_score, rounded)

        return {
            "is_ai_generated": is_ai,
            "ai_score": round(ai_score, 3),
            "indicators": rounded,
            "explanation": explanation,
        }

    def get_detailed_report(self, result: Dict) -> str:
        """Return a formatted multi-line analysis report."""
        if not result or "indicators" not in result:
            return "No analysis result provided."

        lines = ["═" * 50, "  AI Content Detection Report", "═" * 50]
        verdict = "AI-GENERATED" if result["is_ai_generated"] else "HUMAN-WRITTEN"
        lines.append(f"  Verdict : {verdict}")
        lines.append(f"  Score   : {result['ai_score']:.0%}")
        lines.append("─" * 50)

        labels = {
            "vocabulary_richness": "Vocabulary Richness",
            "burstiness": "Burstiness (sentence var.)",
            "sentence_uniformity": "Sentence Uniformity",
            "repeated_phrase_density": "Repeated Phrase Density",
            "personal_pronoun_usage": "Personal Pronoun Usage",
            "hedge_word_frequency": "Hedge / Filler Words",
            "paragraph_uniformity": "Paragraph Uniformity",
            "entropy": "Character Entropy",
        }
        for key, label in labels.items():
            val = result["indicators"].get(key, 0)
            bar = "█" * int(val * 20) + "░" * (20 - int(val * 20))
            lines.append(f"  {label:<28s} {bar} {val:.0%}")

        lines.append("─" * 50)
        lines.append(result.get("explanation", ""))
        lines.append("═" * 50)
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Feature extractors (each returns 0-1, higher = more AI-like)
    # ------------------------------------------------------------------

    def _tokenize(self, text: str) -> List[str]:
        return re.findall(r"[a-zA-Z']+", text.lower())

    def _sentences(self, text: str) -> List[str]:
        parts = re.split(r'(?<=[.!?])\s+', text.strip())
        return [s for s in parts if len(s.split()) >= 3]

    def _vocabulary_richness(self, text: str) -> float:
        words = self._tokenize(text)
        if len(words) < 10:
            return 0.0
        ttr = len(set(words)) / len(words)
        # Lower TTR → more AI-like.  Human TTR typically 0.5-0.8 for short text.
        return max(0.0, min((0.65 - ttr) / 0.35, 1.0))

    def _burstiness(self, text: str) -> float:
        sents = self._sentences(text)
        if len(sents) < 3:
            return 0.0
        lengths = [len(s.split()) for s in sents]
        mean_len = sum(lengths) / len(lengths)
        if mean_len == 0:
            return 0.0
        std = math.sqrt(sum((l - mean_len) ** 2 for l in lengths) / len(lengths))
        cv = std / mean_len  # coefficient of variation
        # Low CV → uniform → AI-like
        return max(0.0, min((0.5 - cv) / 0.5, 1.0))

    def _sentence_uniformity(self, text: str) -> float:
        sents = self._sentences(text)
        if len(sents) < 3:
            return 0.0
        lengths = [len(s.split()) for s in sents]
        mean_len = sum(lengths) / len(lengths)
        if mean_len == 0:
            return 0.0
        diffs = [abs(l - mean_len) for l in lengths]
        avg_diff = sum(diffs) / len(diffs)
        # Low average diff → uniform → AI-like
        return max(0.0, min(1.0 - (avg_diff / mean_len), 1.0))

    def _repeated_phrases(self, text: str) -> float:
        words = self._tokenize(text)
        if len(words) < 10:
            return 0.0
        bigrams = [f"{words[i]} {words[i+1]}" for i in range(len(words) - 1)]
        trigrams = [f"{words[i]} {words[i+1]} {words[i+2]}" for i in range(len(words) - 2)]
        bi_counts = Counter(bigrams)
        tri_counts = Counter(trigrams)
        repeated_bi = sum(c - 1 for c in bi_counts.values() if c > 1)
        repeated_tri = sum(c - 1 for c in tri_counts.values() if c > 1)
        density = (repeated_bi + repeated_tri * 2) / max(len(words), 1)
        return min(density * 5, 1.0)

    def _pronoun_score(self, text: str) -> float:
        words = self._tokenize(text)
        if not words:
            return 0.0
        pronoun_count = sum(1 for w in words if w in self._FIRST_PERSON)
        rate = pronoun_count / len(words)
        # Low pronoun rate → more AI-like
        return max(0.0, min((0.04 - rate) / 0.04, 1.0))

    def _hedge_score(self, text: str) -> float:
        lower = text.lower()
        words_total = max(len(lower.split()), 1)
        count = sum(lower.count(h) for h in self._HEDGE_PHRASES)
        density = count / words_total
        # High hedge density → AI-like
        return min(density * 40, 1.0)

    def _paragraph_uniformity(self, text: str) -> float:
        paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
        if len(paragraphs) < 3:
            return 0.0
        lengths = [len(p.split()) for p in paragraphs]
        mean_len = sum(lengths) / len(lengths)
        if mean_len == 0:
            return 0.0
        std = math.sqrt(sum((l - mean_len) ** 2 for l in lengths) / len(lengths))
        cv = std / mean_len
        return max(0.0, min((0.4 - cv) / 0.4, 1.0))

    def _entropy_score(self, text: str) -> float:
        if not text:
            return 0.0
        freq = Counter(text.lower())
        total = len(text)
        entropy = -sum((c / total) * math.log2(c / total) for c in freq.values() if c > 0)
        # AI text tends toward entropy ~4.0-4.2; human text is broader.
        # Map closeness to 4.1 onto 0-1 scale.
        distance = abs(entropy - 4.1)
        return max(0.0, min(1.0 - (distance / 1.5), 1.0))

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _insufficient_result(self) -> Dict:
        return {
            "is_ai_generated": False,
            "ai_score": 0.0,
            "indicators": {},
            "explanation": "Insufficient text for analysis (need ≥ 30 words).",
        }

    @staticmethod
    def _build_explanation(is_ai: bool, score: float, indicators: Dict) -> str:
        if is_ai:
            parts = ["The text exhibits characteristics common in AI-generated content."]
        else:
            parts = ["The text appears to be human-written."]
        top = sorted(indicators.items(), key=lambda x: x[1], reverse=True)[:3]
        for name, val in top:
            readable = name.replace("_", " ").title()
            parts.append(f"  • {readable}: {val:.0%}")
        return "\n".join(parts)
